[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = [
  'cd backend && pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Backend build completed"']

[start]
cmd = 'cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1'
