[build]
builder = "nixpacks"

[build.nixpacksConfig]
nixPkgs = ["python39", "pip"]

[build.nixpacksConfig.phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[build.nixpacksConfig.phases.build]
cmds = ["echo 'Backend build completed'"]

[build.nixpacksConfig.start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
